language: php

dist: trusty

sudo: false

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
  depth: false

env:
  global:
    - MONOREPO_SPLIT=true
    - SUITE=packages

install:
- composer install

script:
- etc/travis/run-suite script "${SUITE}"

after_script:
# split monorepo to packages - only on merge to master
- |
  if [[ $TRAVIS_EVENT_TYPE == "push" && $MONOREPO_SPLIT == true && $TRAVIS_BRANCH == "master" ]]; then
    make monorepo.install
    make monorepo.split
  fi

notifications:
    email: false