language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
  depth: false

env: MONOREPO_SPLIT=true

install:
- composer install

script:
# echoing something to prevent Travis from running default commands
- echo ":)"

after_script:
# split monorepo to packages - only on merge to master
- |
  if [[ $TRAVIS_EVENT_TYPE == "push" && $MONOREPO_SPLIT == true && $TRAVIS_BRANCH == "master" ]]; then
    vendor/bin/monorepo-builder split -v
  fi